spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: password
      database: demo
      port: 27017
      host: 127.0.0.1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true

